### ISSUE TITLE
Rendre la hierarchie taxonomique cliquable pour faciliter la navigation.

### ISSUE THREAD

**Issue by superornitho** [flore-quebec/species#9]
Rendre la hierarchie taxonomique cliquable pour faciliter la navigation.
![Capture d’écran 2024-02-29 à 02 18 54](https://github.com/flore-quebec/species/assets/59948990/0663f0ca-0344-4a8c-abaf-6a3b77f1d338)

**Comment by frousseu** [comment]
Oui, je me suis surpris à vouloir faire cela aussi en tentant de naviguer. Ce serait très pratique! Merci pour l'explication très claire!

**Comment by frousseu** [comment]
https://github.com/flore-quebec/flore.quebec/commit/21376f7f89e7f489022ebbf751f9b16341599d0f
